---
- name: Configure NGINX repositories
  when: artifactory_nginx_use_official_repos | bool
  become: true
  block:

    - name: Import NGINX signing key
      ansible.builtin.apt_key:
        url: "{{ nginx_repo_signing_key }}"
        state: present

    - name: Add NGINX stable repo
      ansible.builtin.apt_repository:
        repo: "deb {{ artifactory_nginx_official_repo_url }} {{ ansible_facts['ansible_distribution_release'] | lower }} nginx"
        filename: "{{ artifactory_nginx_official_repo_filename }}"
        state: present
        update_cache: true

- name: Install NGINX packages
  become: true
  ansible.builtin.apt:
    name: "{{ artifactory_nginx_os_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
