---
- name: Configure NGINX repositories
  when: nginx_use_official_repos | bool
  block:

    - name: Import NGINX signing key
      become: true
      ansible.builtin.rpm_key:
        key: "{{ nginx_official_repo_signing_key }}"
        state: present

    - name: Add NGINX stable repo
      become: true
      ansible.builtin.yum_repository:
        name: "{{ nginx_official_repo_filename }}"
        description: "{{ nginx_official_repo_description }}"
        file: "{{ nginx_official_repo_filename }}"
        baseurl: "{{ nginx_official_repo_url }}"
        gpgcheck: true
        enabled: true
        module_hotfixes: true
      register: __nginx_setup_repo
      ignore_errors: true

    - name: Fallback to manually adding the repo if the previous task failed
      become: true
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/{{ nginx_official_repo_filename }}.repo"
        owner: root
        group: root
        mode: '0644'
        content: |
          [{{ nginx_official_repo_filename }}]
          name={{ nginx_official_repo_description }}
          baseurl={{ nginx_official_repo_url }}/$releasever/$basearch
          gpgcheck=1
          enabled=1
          gpgkey={{ nginx_official_repo_signing_key }}
          module_hotfixes=true
      when: __nginx_setup_repo is failed

    - name: Update cache
      become: true
      ansible.builtin.dnf:
        state: present
        update_cache: true

- name: Install NGINX
  become: true
  ansible.builtin.dnf:
    name: "{{ nginx_packages }}"
    state: present
    disablerepo: "{{ nginx_disabled_repositories | d(omit, true) }}"
    enablerepo: "{{ nginx_enabled_repositories | d(omit, true) }}"
