---
- name: Configure NGINX repositories
  when: artifactory_nginx_use_official_repos | bool
  become: true
  block:

    - name: Import NGINX signing key
      ansible.builtin.rpm_key:
        key: "{{ artifactory_nginx_official_repo_signing_key }}"
        state: present

    - name: Add NGINX stable repo
      ansible.builtin.yum_repository:
        name: "{{ artifactory_nginx_official_repo_filename }}"
        description: "{{ artifactory_nginx_official_repo_description }}"
        file: "{{ artifactory_nginx_official_repo_filename }}"
        baseurl: "{{ artifactory_nginx_official_repo_url }}"
        gpgcheck: true
        enabled: true
        module_hotfixes: true
      register: __nginx_setup_repo
      ignore_errors: true

    - name: Fallback to manually adding the repo if the previous task failed
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/{{ artifactory_nginx_official_repo_filename }}.repo"
        owner: root
        group: root
        mode: '0644'
        content: |
          [{{ artifactory_nginx_official_repo_filename }}]
          name={{ artifactory_nginx_official_repo_description }}
          baseurl={{ artifactory_nginx_official_repo_url }}/$releasever/$basearch
          gpgcheck=1
          enabled=1
          gpgkey={{ artifactory_nginx_official_repo_signing_key }}
          module_hotfixes=true
      when: __nginx_setup_repo is failed

- name: Clean DNF cache
  become: true
  ansible.builtin.command: dnf clean all
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Install NGINX
  become: true
  ansible.builtin.dnf:
    name: "{{ artifactory_nginx_os_packages }}"
    disablerepo: "{{ artifactory_nginx_disabled_repositories | d(omit, true) }}"
    enablerepo: "{{ artifactory_nginx_enabled_repositories | d(omit, true) }}"
    update_cache: true
    state: present
