---
- name: Install Nginx
  ansible.builtin.yum:
    name: "{{ nginx_packages }}"
    state: present
    disablerepo: "{{ '*' if nginx_setup_repos or not nginx_system_repositories else omit }}"
    enablerepo: "{{ nginx_system_repositories if nginx_setup_repos or not nginx_system_repositories else omit }}"
  become: true
