---
dependencies: []

galaxy_info:
  author: "JFrog Maintainers Team <installers@jfrog.com>"
  description: "The distribution role will install distribution software onto the host. An Artifactory server and Postgress database is required."
  company: JFrog
  issue_tracker_url: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"
  license: license (Apache-2.0)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: Amazon
      versions:
        - 3
  galaxy_tags:
    - distribution
    - jfrog
