- name: Import nginx signing key
  become: true
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repo
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/nginx.list
    owner: root
    group: root
    mode: '0644'
    content: deb {{ nginx_upstream_repo_baseurl }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx
  vars:
    distro_family: "{{ ansible_distribution | lower }}"
    distro_codename: "{{ ansible_distribution_release }}"

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_update_cache
  retries: 5
  delay: 60
  until: apt_update_cache is succeeded