- name: Import nginx signing key
  become: true
  ansible.builtin.rpm_key:
    key: "{{ nginx_upstream_repo_key }}"
    state: present

- name: Add nginx repo
  become: true
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/nginx-main.repo
    owner: root
    group: root
    mode: '0644'
    content: |
        [nginx]
        name=nginx repo
        baseurl={{ nginx_upstream_repo_baseurl }}/{{ (ansible_distribution == 'Amazon') | ternary('amzn','centos') }}/$releasever/$basearch/
        gpgcheck=1
        enabled=1
        gpgkey="{{ nginx_upstream_repo_key }}"
        module_hotfixes=1

- name: Update yum cache
  become: true
  ansible.builtin.yum:
    state: present
    update_cache: true

- name: Gather selinux facts
  ansible.builtin.setup:
    gather_subset: selinux

- name: Set httpd_can_network_connect
  become: true
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: ansible_facts.selinux.status == 'enabled'
