## Note: These values are global and have precedence over role/<product>/defaults/main.yaml
## For production deployments, You may want to generate your master and join keys and apply it to all the nodes.
master_key: ee69d96880726d3abf6b42b97d2ae589111ea95c2a8bd5876ec5cd9e8ee34f86
join_key: 83da88eaaa08dfed5b86888fcec85f19ace0c3ff8747bcefcec2c9769ad4043d

jfrog_url: >-
  "http://{{ hostvars[groups['artifactory_servers'][0]]['ansible_host'] }}:8082"

## Products enabled
artifactory_enabled: true
xray_enabled: true
distribution_enabled: true
insight_enabled: true
postgres_enabled: true

# Artifactory DB details
artifactory_db_type: postgresql
artifactory_db_driver: org.postgresql.Driver
artifactory_db_name: artifactory
artifactory_db_user: artifactory
artifactory_db_password: password
artifactory_db_url: >-
  jdbc:postgresql://{{ hostvars[groups['postgres_servers'][0]]['ansible_host'] }}:5432/{{ artifactory_db_name }}

# Xray DB details
xray_db_type: postgresql
xray_db_driver: org.postgresql.Driver
xray_db_name: xray
xray_db_user: xray
xray_db_password: password
xray_db_url: >-
  postgres://{{ hostvars[groups['postgres_servers'][0]]['ansible_host'] }}:5432/{{ xray_db_name }}?sslmode=disable

# Distribution DB details
distribution_db_type: postgresql
distribution_db_driver: org.postgresql.Driver
distribution_db_name: distribution
distribution_db_user: distribution
distribution_db_password: password
distribution_db_url: >-
  jdbc:postgresql://{{ hostvars[groups['postgres_servers'][0]]['ansible_host'] }}:5432/{{ distribution_db_name }}?sslmode=disable

# Insight DB details
insight_db_type: postgresql
insight_db_driver: org.postgresql.Driver
insight_db_name: insight
insight_db_user: insight
insight_db_password: password
insight_db_url: >-
  jdbc:postgresql://{{ hostvars[groups['postgres_servers'][0]]['ansible_host'] }}:5432/{{ insight_db_name }}?sslmode=disable

# Postgresql users and databases/schemas
database:
  artifactory:
    name: "{{ artifactory_db_name }}"
    owner: "{{ artifactory_db_user }}"
    username: "{{ artifactory_db_user }}"
    password: "{{ artifactory_db_password }}"
    enabled: "{{ artifactory_enabled }}"
  xray:
    name: "{{ xray_db_name }}"
    owner: "{{ xray_db_user }}"
    username: "{{ xray_db_user }}"
    password: "{{ xray_db_password }}"
    enabled: "{{ xray_enabled }}"
  distribution:
    name: "{{ distribution_db_name }}"
    owner: "{{ distribution_db_user }}"
    username: "{{ distribution_db_user }}"
    password: "{{ distribution_db_password }}"
    enabled: "{{ distribution_enabled }}"
  insight:
    name: "{{ insight_db_name }}"
    owner: "{{ insight_db_user }}"
    username: "{{ insight_db_user }}"
    password: "{{ insight_db_password }}"
    enabled: "{{ insight_enabled }}"

# For Centos/RHEL-7, Set this to "/usr/bin/python"
ansible_python_interpreter: "/usr/bin/python3"
