---
# handlers file for artifactory_nginx

- name: Update CA trust store
  become: true
  ansible.builtin.command: "{{ system_trust_store_update }}"

- name: Restart NGINX
  become: true
  ansible.builtin.systemd_service:
    name: "{{ nginx_system_daemon }}"
    state: restarted
