---
# handlers file for artifactory_nginx

- name: Update CA trust store
  become: true
  ansible.builtin.command: "{{ artifactory_nginx_os_cmd_truststore_update }}"

- name: Restart NGINX
  become: true
  ansible.builtin.systemd_service:
    name: "{{ artifactory_nginx_os_daemon }}"
    state: restarted
