---
project_name: JFrog
reference: "https://github.com/robertdebock/ansible-role-artifactory/blob/master/defaults/main.yml"
versions:
  - name: Artifactory
    url: "https://releases.jfrog.io/artifactory/"
