---
# defaults file for artifactory
# indicates were this collection was downlaoded from (galaxy, automation_hub, standalone)
ansible_marketplace: standalone

# The version of Artifactory to install
artifactory_version: 7.15.3

# licenses - cluster license content in json
artifactory_licenses:

# whether to enable HA
artifactory_ha_enabled: true

# value for whether a host is primary. this should be set in host vars
artifactory_is_primary: true

# The location where Artifactory should install.
artifactory_download_directory: /opt/jfrog

# The location where Artifactory should store data.
artifactory_file_store_dir: /data

# whether to customer data directory
use_custom_data_directory: false

# location for customer directory. Will be symlink to as artifactory/var
custom_data_directory: /artifactory-user-data

# Pick the Artifactory flavour to install, can be also cpp-ce, jcr, pro.
artifactory_flavour: pro

extra_java_opts: -server -Xms2g -Xmx14g -Xss256k -XX:+UseG1GC

artifactory_tar: https://releases.jfrog.io/artifactory/artifactory-pro/org/artifactory/{{ artifactory_flavour }}/jfrog-artifactory-{{ artifactory_flavour }}/{{ artifactory_version }}/jfrog-artifactory-{{ artifactory_flavour }}-{{ artifactory_version }}-linux.tar.gz
artifactory_home: "{{ artifactory_download_directory }}/artifactory-{{ artifactory_flavour }}-{{ artifactory_version }}"

artifactory_user: artifactory
artifactory_group: artifactory

# Set the parameters required for the service.
service_list:
  - name: artifactory
    description: Start script for Artifactory
    start_command: "{{ artifactory_home }}/bin/artifactory.sh start"
    stop_command: "{{ artifactory_home }}/bin/artifactory.sh stop"
    type: forking
    status_pattern: artifactory
    user_name: "{{ artifactory_user }}"
    group_name: "{{ artifactory_group }}"

product_id: CloudFormation_QS_EC2/1.0.0
