- name: Play for artifactory_servers
  hosts: artifactory_servers
  collections:
    - community.general
  serial:
    - 1
    - 100%
  roles:
    - role: artifactory
      when: artifactory_enabled | bool
