default_postgresql_bin_path: /usr/pgsql-{{ postgres_version }}/bin
default_postgresql_config_path: /var/lib/pgsql/{{ postgres_version }}/data
default_postgresql_data_dir: /var/lib/pgsql/{{ postgres_version }}/data
default_postgresql_daemon: postgresql-{{ postgres_version }}.service
default_postgresql_external_pid_file: /var/run/postgresql/{{ postgres_version }}-main.pid
