---
- name: Check if artifactory archive already exists
  become: true
  ansible.builtin.stat:
    path: "{{ jfrog_home_directory }}/{{ artifactory_tar_file_name }}"
  register: artifactory_tar_check

- name: Download artifactory archive
  become: true
  ansible.builtin.get_url:
    url: "{{ artifactory_tar }}"
    timeout: "{{ artifactory_download_timeout }}"
    dest: "{{ jfrog_home_directory }}"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: '0644'
  register: download_artifactory
  until: download_artifactory is succeeded
  retries: 3
  when: not artifactory_tar_check.stat.exists

- name: Extract artifactory archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ jfrog_home_directory }}/{{ artifactory_tar_file_name }}"
    dest: "{{ jfrog_home_directory }}"
    remote_src: true
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_untar_home }}"
  register: unarchived_artifactory
  when:
    - not ansible_check_mode
    - download_artifactory is succeeded
