---
- name: Check if artifactory archive already exists
  become: true
  ansible.builtin.stat:
    path: "{{ artifactory_jfrog_dir }}/{{ artifactory_tar_name }}"
  register: __stat_artifactory_tar

- name: Download artifactory archive
  become: true
  ansible.builtin.get_url:
    url: "{{ artifactory_tar_url }}"
    timeout: "{{ artifactory_download_timeout }}"
    dest: "{{ artifactory_jfrog_dir }}"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: '0644'
  register: __download_artifactory_tar
  until: __download_artifactory_tar is succeeded
  retries: 3
  when: not __stat_artifactory_tar.stat.exists

- name: Extract artifactory archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ artifactory_jfrog_dir }}/{{ artifactory_tar_name }}"
    dest: "{{ artifactory_jfrog_dir }}"
    remote_src: true
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_untar_dir }}"
  register: unarchived_artifactory
  when:
    - not ansible_check_mode
    - __download_artifactory_tar is succeeded
