---
- name: Ensure user ownership of files in jfrog_home_directory is correct
  become: true
  ansible.builtin.command: >-
    find {{ artifactory_jfrog_dir }} ! -user {{ artifactory_user }}
    -print -exec chown {{ artifactory_user }} {} \;
  register: __fix_user_ownerships
  changed_when: __fix_user_ownerships.stdout_lines | length > 0

- name: Ensure group ownership of files in artifactory_jfrog_dir is correct
  become: true
  ansible.builtin.command: >-
    find {{ artifactory_jfrog_dir }} ! -group {{ artifactory_group }}
    -print -exec chgrp {{ artifactory_group }} {} \;
  register: __fix_group_ownerships
  changed_when: __fix_group_ownerships.stdout_lines | length > 0
