---
dependencies: []

galaxy_info:
  author: "JFrog Maintainers Team <installers@jfrog.com>"
  description: "The artifactory_nginx_ssl role installs and configures nginx for SSL."
  company: JFrog
  issue_tracker_url: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"
  license: license (Apache-2.0)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - artifactory
    - jfrog