- name: Install prerequisite packages
  become: yes
  yum:
    name: ['net-tools', '{{ selinux_policy_package }}']
    state: present

- name: Configure SELinux context
  include_tasks: shared/selinux_configure_context.yml
