- name: Perform installation
  include_tasks: "install.yml"
  when:
    - distribution_enabled
    - not distribution_upgrade_only

- name: Perform upgrade
  include_tasks: "upgrade.yml"
  when:
    - distribution_enabled
    - distribution_upgrade_only
