---
# handlers file for insight
- name: Restart insight
  become: true
  ansible.builtin.systemd:
    name: "{{ insight_daemon }}"
    state: restarted

- name: Stop insight
  become: true
  ansible.builtin.systemd:
    name: "{{ insight_daemon }}"
    state: stopped

- name: Reload systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
