# In this file users, backendroles and hosts can be mapped to Search Guard roles.
# Permissions for Search Guard roles are configured in sg_roles.yml
_sg_meta:
  type: "rolesmapping"
  config_version: 2

## Demo roles mapping
SGS_ALL_ACCESS:
  description: "Maps admin to SGS_ALL_ACCESS"
  reserved: true
  backend_roles:
    - "admin"

SGS_OWN_INDEX:
  description: "Allow full access to an index named like the username"
  reserved: false
  users:
    - "*"

SGS_LOGSTASH:
  reserved: false
  backend_roles:
    - "logstash"

SGS_KIBANA_USER:
  description: "Maps kibanauser to SGS_KIBANA_USER"
  reserved: false
  backend_roles:
    - "kibanauser"

SGS_READALL:
  reserved: true
  backend_roles:
    - "readall"

SGS_MANAGE_SNAPSHOTS:
  reserved: true
  backend_roles:
    - "snapshotrestore"

SGS_KIBANA_SERVER:
  reserved: true
  users:
    - "kibanaserver"

sg_anonymous:
  backend_roles:
    - sg_anonymous_backendrole
