---
- name: Configure bootstrap.creds file
  become: true
  ansible.builtin.template:
    src: 'bootstrap.creds.j2'
    dest: "{{ artifactory_dir }}/var/etc/access/bootstrap.creds"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: '0600'
  when:
    - artifactory_admin_username | d('') | length > 0
    - artifactory_admin_password | d('') | length > 0
  notify: Restart artifactory
