---
- name: Configure installer-info.json file
  become: true
  ansible.builtin.template:
    src: 'installer-info.json.j2'
    dest: "{{ artifactory_dir }}/var/etc/artifactory/info/installer-info.json"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: '0644'
    backup: true
  notify: Restart artifactory
