---
- name: Check if system.yaml exists
  become: true
  ansible.builtin.stat:
    path: "{{ artifactory_dir }}/var/etc/system.yaml"
  register: stat_system_yaml

- name: Configure system.yaml file
  become: true
  ansible.builtin.copy:
    content: "{{ artifactory_systemyaml }}"
    dest: "{{ artifactory_dir }}/var/etc/system.yaml"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: '0644'
    backup: true
  when: not stat_system_yaml.stat.exists
  notify: Restart artifactory
