# Copyright (c) 2026 JFrog Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0.
# See LICENSE file in the project root for full license information.
---

dsl_definitions:
  ingress_nginx_repo_config: &ingress_nginx_repo_config
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

node_templates:

  ingress_nginx_repo:
    type: dell.nodes.helm.Repo
    properties:
      resource_config: *ingress_nginx_repo_config
    relationships:
      - target: helm_binary
        type: dell.relationships.helm.run_on_host

  ingress_nginx_release:
    type: dell.nodes.helm.Release
    properties:
      client_config: { get_secret: { get_input: k8s_credentials } }
      resource_config:
        name: ingress-nginx
        chart: ingress-nginx/ingress-nginx
        set_values:
          - name: controller.config.use-forwarded-headers
            value: "true"
        flags:
          - name: namespace
            value: ingress-nginx
          - name: create-namespace
          - name: version
            value: { get_input: ingress_nginx_version }
          - name: atomic
          - name: wait
          - name: timeout
            value: "5m0s"
    capabilities:
      scalable:
        properties:
          default_instances: { get_input: install_ingress_controller }
    relationships:
      - target: helm_binary
        type: dell.relationships.helm.run_on_host
      - target: ingress_nginx_repo
        type: dell.relationships.depends_on
