---
# handlers file for missioncontrol
- name: restart missioncontrol
  become: yes
  systemd:
    name: "{{ mc_daemon }}"
    state: restarted

- name: stop missioncontrol
  become: yes
  systemd:
    name: "{{ mc_daemon }}"
    state: stopped