- name: Create the access.config.patch.yml file
  become: true
  template:
    src: access-config-patch.yml.j2
    dest: "{{ artifactory_home }}/var/etc/access/access.config.patch.yml"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0644
  notify: Restart artifactory
  when:
    - artifactory_access_config_patch is defined
    - artifactory_access_config_patch | length > 0