apiVersion: v1
appVersion: 3.5.2
description: Universal component scan for security and license inventory and impact analysis
sources:
- https://bintray.com/jfrog/product/xray/view
- https://github.com/jfrog/charts
keywords:
- xray
- jfrog
maintainers:
- email: vinaya@jfrog.com
  name: Vinay Aggarwal
- email: johnp@jfrog.com
  name: John Peterson
name: openshift-xray
version: 3.5.1
