- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    name: ['acl', 'apt-transport-https', 'locales', 'python3-psycopg2']
    state: present
    update_cache: true

- name: Ensure UTF-8 locale exists
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Import PostgreSQL repository key
  become: true
  ansible.builtin.apt_key:
    url: "{{ postgres_apt_key_url }}"
    id: "{{ postgres_apt_key_id }}"
    state: present
  register: download_postgresql_key
  until: download_postgresql_key is success
  retries: 3
  delay: 3

- name: Register PostgreSQL repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ postgres_apt_repository_repo }}"
    state: present
    filename: pgdg
  register: download_postgresql_repo
  until: download_postgresql_repo is success
  retries: 3
  delay: 3

- name: Install postgres packages
  become: true
  ansible.builtin.apt:
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-contrib-{{ postgres_version }}
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: download_postgresql
  until: download_postgresql is success
  retries: 3
  delay: 3
