---
- hosts: postgres_servers
  collections:
    - jfrog.platform
  roles:
    - role: postgres
      when: postgres_enabled | bool

- hosts: artifactory_servers
  collections:
    - jfrog.platform
  serial:
    - 1
    - 100%
  roles:
    - role: artifactory
      when: artifactory_enabled | bool
