- name: Ensure files ownership are correct
  become: true
  ansible.builtin.command:
    cmd: >-
      find "{{ jfrog_home_directory }}" -xdev
      ( ! -user "{{ xray_user }}" -o ! -group "{{ xray_group }}" )
      -print -exec chown -h "{{ xray_user }}:{{ xray_group }}" {} +
  register: xray_ownerships
  changed_when: xray_ownerships.stdout | length > 0
