apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: registry.connect.redhat.com/jfrog/xray-rabbitmq:3.8.9
          imagePullPolicy: "Always"
          name: xray-rabbitmq
          ports:
            -  containerPort: 4369
            -  containerPort: 5672
            -  containerPort: 15672
