- debug:
    msg: "Performing installation of missionControl version - {{ missioncontrol_version }}"

- name: Install prerequisite packages
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure group jfmc exist
  become: yes
  group:
    name: "{{ mc_group }}"
    state: present

- name: Ensure user jfmc exist
  become: yes
  user:
    name: "{{ mc_user }}"
    group: "{{ mc_group }}"
    create_home: yes
    home: "{{ mc_home }}"
    shell: /bin/bash
    state: present

- name: Check if mc tar exists
  become: yes
  stat:
    path: "{{ jfrog_home_directory }}/{{ mc_tar_file_name }}"
  register: mc_tar_check

- name: Download mc
  become: yes
  get_url:
    url: "{{ mc_tar }}"
    timeout: "{{ mc_download_timeout }}"
    dest: "{{ jfrog_home_directory }}"
  register: download_mc
  until: download_mc is succeeded
  retries: 3
  when: not mc_tar_check.stat.exists

- name: Extract mc tar
  become: yes
  unarchive:
    src: "{{ jfrog_home_directory }}/{{ mc_tar_file_name }}"
    dest: "{{ jfrog_home_directory }}"
    remote_src: true
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"
    creates: "{{ mc_untar_home }}"
  when: download_mc is succeeded

- name: Check if app directory exists
  become: yes
  stat:
    path: "{{ mc_home }}/app"
  register: app_dir_check

- name: Copy untar directory to mc home
  become: yes
  command: "cp -r {{ mc_untar_home }}/. {{ mc_home }}"
  when: not app_dir_check.stat.exists

- name: Create required directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"
  loop:
    - "{{ mc_home }}/var/etc"
    - "{{ mc_home }}/var/etc/security/"
    - "{{ mc_home }}/var/etc/info/"

- name: Configure master key
  become: yes
  copy:
    dest: "{{ mc_home }}/var/etc/security/master.key"
    content: "{{ master_key }}"
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"
    mode: 0640

- name: Setup elasticsearch
  import_tasks: setup-elasticsearch.yml

- name: Check if install.sh wrapper script exist
  become: yes
  stat:
    path: "{{ mc_install_script_path }}/install.sh"
  register: install_wrapper_script

- name: Include interactive installer scripts
  include_vars: script/archive.yml

- name: Install JFMC
  include_tasks: expect.yml
  vars:
    exp_executable_cmd: "./install.sh -u {{ mc_user }} -g {{ mc_group }}"
    exp_dir: "{{ mc_install_script_path }}"
    exp_scenarios: "{{ mc_installer_scenario['main'] }}"
  args:
    apply:
      environment:
        YQ_PATH: "{{ mc_thirdparty_path }}/yq"
  when: install_wrapper_script.stat.exists

- name: Configure installer info
  become: yes
  template:
    src: installer-info.json.j2
    dest: "{{ mc_home }}/var/etc/info/installer-info.json"
  notify: restart missioncontrol

- name: Check if systemyaml exists
  become: yes
  stat:
    path: "{{ mc_home }}/var/etc/system.yaml"
  register: systemyaml

- name: Configure systemyaml
  become: yes
  template:
    src: "{{ mc_system_yaml_template }}"
    dest: "{{ mc_home }}/var/etc/system.yaml"
  when:
    - mc_systemyaml is defined
    - mc_systemyaml|length > 0
    - mc_systemyaml_override or (not systemyaml.stat.exists)
  notify: restart missioncontrol

- name: Update correct permissions
  become: yes
  file:
    path: "{{ mc_home }}"
    state: directory
    recurse: yes
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"

- name: Install mc as a service
  become: yes
  shell: "{{ mc_archive_service_cmd }}"
  args:
    chdir: "{{ mc_install_script_path }}"
    creates: "{{ mc_service_file }}"
  register: check_service_status_result

- name: Restart missioncontrol
  meta: flush_handlers

- name: Make sure missionControl is up and running
  uri:
    url: http://127.0.0.1:8082/router/api/v1/system/health
    timeout: 130
    status_code: 200
  register: result
  until: result is succeeded
  retries: 25
  delay: 5
  when: not ansible_check_mode
