- name: perform installation
  include_tasks: "install.yml"
  when: 
    - mc_enabled
    - not mc_upgrade_only
- name: perform upgrade
  include_tasks: "upgrade.yml"
  when:
    - mc_enabled
    - mc_upgrade_only