- name: Ensure group elasticsearch exists
  become: yes
  group:
    name: elasticsearch
    state: present

- name: Ensure user elasticsearch exists
  become: yes
  user:
    name: elasticsearch
    group: elasticsearch
    create_home: yes
    home: "{{ mc_es_home }}"
    shell: /bin/bash
    state: present

- name: Create required directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: elasticsearch
    group: elasticsearch
  loop:
    - "{{ mc_es_conf_base }}"
    - "{{ mc_es_data_dir }}"
    - "{{ mc_es_log_dir }}"
    - "{{ mc_es_home }}"

- name: Set max file descriptors limit
  become: yes
  pam_limits:
    domain: 'elasticsearch'
    limit_type: '-'
    limit_item: nofile
    value: '65536'

- name: Update nproc limit
  become: yes
  pam_limits:
    domain: 'elasticsearch'
    limit_type: '-'
    limit_item: nproc
    value: '4096'

- name: Set vm.max_map_count in /etc/sysctl.conf
  become: yes
  ignore_errors: yes
  sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes

- name: Find elasticsearch package
  become: yes
  find:
    paths: "{{ mc_home }}/app/third-party/elasticsearch"
    patterns: "^elasticsearch-.+\\.tar.gz$"
    use_regex: yes
    file_type: file
  register: check_elasticsearch_package_result

- name: Set elasticsearch package file name
  set_fact:
    mc_elasticsearch_package: "{{ check_elasticsearch_package_result.files[0].path }}"
  when: check_elasticsearch_package_result.matched > 0

- name: Ensure /usr/share/elasticsearch  exists
  become: yes
  file:
    path: "{{ mc_es_home }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch

- name: Extract elasticsearch package
  become: yes
  ignore_errors: yes
  unarchive:
    src: "{{ mc_elasticsearch_package }}"
    dest: "{{ mc_es_home }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1
    owner: elasticsearch
    group: elasticsearch
    creates: "{{ mc_es_java_home }}"
  register: unarchive_result
  when: check_elasticsearch_package_result.matched > 0

- name: Copy elasticsearch config files to ES_PATH_CONF dir
  become: yes
  command: "cp -r {{ mc_es_home }}/config/. {{ mc_es_conf_base }}/"
  when: unarchive_result.changed

- name: Remove elasticsearch config dir
  become: yes
  file:
    path: "{{ mc_es_home }}/config"
    state: absent
  when: unarchive_result.changed

- name: Generate HA elasticsearch.yml template file
  become: yes
  ignore_errors: yes
  template:
    src: templates/ha/{{ mc_ha_node_type }}.elasticsearch.yml.j2
    dest: "{{ mc_es_conf_base }}/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
  when: unarchive_result.extract_results.rc | default(128) == 0

- name: Generate elasticsearch.yml template file
  become: yes
  template:
    src: templates/elasticsearch.yml.j2
    dest: "{{ mc_es_conf_base }}/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
  when: unarchive_result.extract_results.rc | default(128) == 0

- name: Create empty unicast_hosts.txt file
  become: yes
  file:
    path: "{{ mc_es_conf_base }}/unicast_hosts.txt"
    state: touch
    mode: 0664
    owner: elasticsearch
    group: elasticsearch

- name: Setup searchguard plugin
  import_tasks: setup-searchguard.yml

- name: Update directories permissions
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: elasticsearch
    group: elasticsearch
  loop:
    - "{{ mc_es_conf_base }}"
    - "{{ mc_es_data_dir }}"
    - "{{ mc_es_log_dir }}"
    - "{{ mc_es_home }}"

- name: Start elasticsearch
  become: yes
  shell: "su -c '{{ mc_es_script_path }}/elasticsearch -d' elasticsearch"
  environment:
    ES_JAVA_HOME: "{{ mc_es_java_home }}"
    ES_PATH_CONF: "{{ mc_es_conf_base }}/"
  register: start_elasticsearch
  when: unarchive_result.extract_results.rc | default(128) == 0

- name: Wait for elasticsearch to start
  pause:
    seconds: 30
  when: start_elasticsearch.changed

- name: Check if elasticsearch is running
  wait_for:
    host: localhost
    port: "{{ mc_es_transport_port }}"
    delay: 5
    connect_timeout: 1

- name: Init searchguard plugin
  become: yes
  shell: |
    ./sgadmin.sh -p {{ mc_es_transport_port }} -cacert root-ca.pem \
    -cert sgadmin.pem -key sgadmin.key -cd {{ mc_es_searchgaurd_home }}/sgconfig/ -nhnv -icl
  args:
    chdir: "{{ mc_es_searchgaurd_home }}/tools/"
  environment:
    JAVA_HOME: "{{ mc_es_java_home }}"
  register: install_searchguard_result
  when: check_searchguard_bundle_result.matched == 1