- debug:
    msg: "Performing Upgrade of missionControl version - {{ missioncontrol_version }}"

- name: Check if mc tar exists
  become: yes
  stat:
    path: "{{ jfrog_home_directory }}/{{ mc_tar_file_name }}"
  register: mc_tar_check

- name: Download mc for upgrade
  become: yes
  get_url:
    url: "{{ mc_tar }}"
    timeout: "{{ mc_download_timeout }}"
    dest: "{{ jfrog_home_directory }}"
  register: download_mc
  until: download_mc is succeeded
  retries: 3
  when: not mc_tar_check.stat.exists

- name: Extract mc tar
  become: yes
  unarchive:
    src: "{{ jfrog_home_directory }}/{{ mc_tar_file_name }}"
    dest: "{{ jfrog_home_directory }}"
    remote_src: true
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"
    creates: "{{ mc_untar_home }}"
  when: download_mc is succeeded

- name: Stop mc service
  become: yes
  systemd:
    name: "{{ mc_daemon }}"
    state: stopped
  when: download_mc.changed

- name: Delete current app folder
  become: yes
  file:
    path: "{{ mc_home }}/app"
    state: absent
  when: download_mc.changed

- name: Copy new app to mc app
  command: "cp -r {{ mc_untar_home }}/app/. {{ mc_home }}/app"
  become: yes
  when: download_mc.changed

- name: Delete untar directory
  file:
    path: "{{ mc_untar_home }}"
    state: absent
  become: yes
  when: download_mc.changed

- name: Upgrade elasticsearch
  import_tasks: upgrade-elasticsearch.yml
  when: download_mc.changed

- name: Check if systemyaml exists
  become: yes
  stat:
    path: "{{ mc_home }}/var/etc/system.yaml"
  register: systemyaml

- name: Configure systemyaml
  become: yes
  template:
    src: "{{ mc_system_yaml_template }}"
    dest: "{{ mc_home }}/var/etc/system.yaml"
  when:
    - mc_systemyaml is defined
    - mc_systemyaml|length > 0
    - mc_systemyaml_override or (not systemyaml.stat.exists)
  notify: restart missioncontrol

- name: Check if install.sh wrapper script exist
  become: yes
  stat:
    path: "{{ mc_install_script_path }}/install.sh"
  register: upgrade_wrapper_script
  when: download_mc.changed

- name: Include interactive installer scripts
  include_vars: script/archive.yml

- name: Upgrade JFMC
  include_tasks: expect.yml
  vars:
    exp_executable_cmd: "./install.sh -u {{ mc_user }} -g {{ mc_group }}"
    exp_dir: "{{ mc_install_script_path }}"
    exp_scenarios: "{{ mc_installer_scenario['main'] }}"
  args:
    apply:
      environment:
        YQ_PATH: "{{ mc_thirdparty_path }}/yq"
  when:
    - upgrade_wrapper_script.stat.exists
    - download_mc.changed

- name: Configure installer info
  become: yes
  template:
    src: installer-info.json.j2
    dest: "{{ mc_home }}/var/etc/info/installer-info.json"
  notify: restart missioncontrol

- name: Update correct permissions
  become: yes
  file:
    path: "{{ mc_home }}"
    state: directory
    recurse: yes
    owner: "{{ mc_user }}"
    group: "{{ mc_group }}"

- name: Restart missioncontrol
  meta: flush_handlers

- name: Make sure missionControl is up and running
  uri:
    url: http://127.0.0.1:8082/router/api/v1/system/health
    timeout: 130
    status_code: 200
  register: result
  until: result is succeeded
  retries: 25
  delay: 5
  when: not ansible_check_mode
