# Copyright (c) 2026 JFrog Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0.
# See LICENSE file in the project root for full license information.
---

dsl_definitions:
  ingress_nginx_repo_config: &ingress_nginx_repo_config
    name: ingress-nginx
    repo_url: { get_input: ingress_nginx_repo_url }

node_templates:

  fetch_labels:
    type: dell.nodes.Root
    interfaces:
      dell.interfaces.lifecycle:
        start: |
          from dell import ctx
          from dell.manager import get_rest_client
          
          client = get_rest_client()
          this_dep = client.deployments.get(ctx.deployment.id)
          target_dep = client.deployments.get(this_dep.inputs["target_deployment_id"])
          labels = []
          ctx.logger.info("current labels: {}".format(this_dep.labels))
          for label in this_dep.labels:
            labels.append({label.key: label.value})
          ctx.logger.info("target_dep labels: {}".format(target_dep.labels))
          labels.append({"target_id": [label.value for label in target_dep.labels if label.get("key") == "target_id"][0]})
          
          ctx.logger.info("updating labels to: {}".format(labels))
          client.deployments.update_labels(ctx.deployment.id, labels)

  fetch_k8s_config_secret:
    type: dell.nodes.Root
    interfaces:
      dell.interfaces.lifecycle:
        precreate:
          implementation: application/scripts/parse_k8s_secret.py
          executor: central_deployment_agent
          inputs:
            k8s_credentials: { get_input: k8s_credentials }

  helm_binary:
    type: dell.nodes.helm.Binary

  ingress_nginx_repo:
    type: dell.nodes.helm.Repo
    properties:
      resource_config: *ingress_nginx_repo_config
    relationships:
      - target: helm_binary
        type: dell.relationships.helm.run_on_host

  ingress_nginx_release:
    type: dell.nodes.helm.Release
    properties:
      client_config: { get_attribute: [fetch_k8s_config_secret, k8s_client_config] }
      rollback: false
      resource_config:
        name: { get_input: release_name }
        chart: ingress-nginx/ingress-nginx
        set_values:
          - name: controller.config.use-forwarded-headers
            value: "true"
        flags:
          - name: namespace
            value: { get_input: namespace }
          - name: create-namespace
          - name: version
            value: { get_input: ingress_nginx_version }
          - name: atomic
          - name: wait
          - name: timeout
            value: "5m0s"
    relationships:
      - target: helm_binary
        type: dell.relationships.helm.run_on_host
      - target: ingress_nginx_repo
        type: dell.relationships.depends_on
      - target: fetch_k8s_config_secret
        type: dell.relationships.depends_on

capabilities:
  release_name:
    description: Name of the ingress-nginx Helm release
    value: { get_input: release_name }
  namespace:
    description: Namespace where ingress-nginx is installed
    value: { get_input: namespace }
